
FROM ubuntu:19.10

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y apt-utils \
    && apt-get install -y python3 python3-pip rsync vim wget curl pigz pkg-config git samtools minimap2

RUN groupadd -g 1001 -r ont \
    && useradd -r -u 999 -g ont ont -s /bin/bash \
    && mkdir /home/ont \
    && chown ont:ont /home/ont

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash \
    && apt-get install -y nodejs

# handle python and jupyter stuff
RUN pip3 install --upgrade pip \
    && pip install wheel setuptools \
    && pip install pybind11 \
    && pip install Cython --find-links file:///tmp \
    && pip install scipy pysam binlorry biopython snakemake \
    && pip install git+https://github.com/artic-network/Porechop.git@v0.3.2pre \
    && pip install git+https://github.com/artic-network/fieldbioinformatics.git

# clean up ....
RUN apt-get autoremove -y \
    && apt-get clean \
    && rm -fR /tmp/* \
    && chown -R ont /usr/lib/node_modules \
    && mkdir /data \
    && mkdir /data/pass \
    && mkdir /data/annotations \
    && chown -R ont:ont /data

USER ont:ont

COPY docker_workflow.sh /tmp/docker_workflow.sh

RUN cd /home/ont \
    && git clone https://github.com/iiSeymour/rampart.git  \
    && cd rampart \
    && npm install \
    && npm run build \
    && npm install --no-bin-links -g . \
    && cd /home/ont \
    && git clone --recursive https://github.com/artic-network/artic-ncov2019.git \
    && cd /data \
    && wget https://raw.githubusercontent.com/artic-network/artic-ncov2019/master/simulated_reads.tgz \
    && tar -zxvpf simulated_reads.tgz \
    && mv simulated_reads/* pass/

USER root:root

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10 \
    && cd /opt/ \
    && wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 \
    && tar -jxvpf phantomjs-2.1.1-linux-x86_64.tar.bz2 \
    && cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/ \
    && apt-get install -y nmap iptables 

USER ont:ont

COPY docker_workflow.sh /tmp/docker_workflow.sh
RUN echo 'alias rampart=/usr/lib/node_modules/artic-rampart/rampart.js\n' >> /home/ont/.bashrc \
    && cp /tmp/docker_workflow.sh /home/ont/docker_workflow.sh \
    && chmod +x /home/ont/docker_workflow.sh

WORKDIR /home/ont
EXPOSE 3000 3001

# ENTRYPOINT ["/home/ont/docker_workflow.sh"]
